title: Your Site Title
theme: jekyll-theme-cayman
url: "https://documentation-temporary.github.io" # Your domain name, including http:// or https://

just_the_docs:
  show_sidebar: true
  collections:
    - name: "Docs"
      output: true

# Navigation menu
header_pages:
  - index.md
  - docs/workspace.md
  - docs/accessibility.md

# Configuration for the sidebar (manually added sidebar support)
sidebar:
  nav_title: "Site Navigation" # Sidebar title
  nav:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    - title: "Contact"
      url: "/contact/"