     theme: "just-the-docs"
     just_the_docs:
       aux_links:
         Installation Guide: /docs/install.md
         Introduction: /docs/intro.md
       collections:
         docs:
           output: true
